safenet_cms:
    resource: "@SafenetCMSBundle/Resources/config/routing.yml"
    prefix:   /
user_controller:
    resource: "@UserBundle/Controller/"
    type: annotation
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation