# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    mirza: 
                        password: mirza
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
                    
    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: login
            logout: 
                path: _demo_logout
                target: _demo
            anonymous: ~
    access_control: 
        - {path: /add, roles: ROLE_USER}